### ISSUE TITLE
Error upgrading kubernetes cluster version.

### ISSUE THREAD

**Issue by skydjol** [ovh/terraform-provider-ovh#362] opened 2023-01-18 16:40 UTC
### Terraform Version
Terraform v1.3.6

### Affected Resource(s)
- ovh_cloud_project_kube

### Terraform Configuration Files
```hcl
resource "ovh_cloud_project_kube" "cluster" {
  service_name       = var.ovh.project
  name               = "cluster_name"
  region             = var.ovh.region
  version            = var.kube_version
  private_network_id = var.private_network_id

  update_policy = "NEVER_UPDATE"

  lifecycle {
    prevent_destroy = true
  }
}
```

### Debug Output
https://gist.github.com/skydjol/f2a0d9e4f152d6067957f729f6713c46

### Expected Behavior
Upgrade to the version specified in terraform.

### Actual Behavior
terraform exits in error.

```
│ Error: HTTP Error 409: Client::Conflict: "409: Update aborted for service xxxxxxxxx because of policy NEVER_UPDATE (request ID: xxxxxxxxx)" (X-OVH-Query-Id: xxxxxxxxx)
```

### Steps to Reproduce
1. `create cluster in 1.22 with terraform module`
2. `update cluster in 1.23 with terraform module`

**Comment by yomovh** [comment] 2023-01-19 08:56
Issue reproduced with provider 0.26. 

Here is a work around to make your upgrade and still have the `NEVER_UPDATE` state afterwards.

1. set `update_policy`to `MINIMAL_DOWNTIME`
2. run `terraform apply`
3. set the `version` to your target version
4. run `terraform apply` : this will upgrade the version of your cluster
5. set `update_policy`to `NEVER_UPDATE`
6. run `terraform apply`

I will continue investigating with the product team to be sure this behavior is as expected. If this is the case, we will add it in the documentation.

**Comment by yomovh** [comment] 2023-03-01 09:53
Reopening to followup the documentation update

**Comment by LisaPerrier** [comment] 2023-03-02 15:51
Hello @skydjol, 
 We have taken this taken this issue under consideration and have made the necessary. It should be resolved in 2 weeks.

**Comment by LisaPerrier** [comment] 2023-03-23 16:20
Hello all, closing this issue since it has been fixed :)

**Comment by yomovh** [comment] 2023-03-24 10:13
@skydjol : the workaround described above is not anymore needed, the API have been changed to allow update even when `update_policy` is set to `NEVER_UPDATE`

**Closed by yomovh** 2023-03-24 10:13 UTC
Labels: Type: Documentation, Product: Managed Kubernetes Service, Status: Backlog
