### ISSUE TITLE
ovh provider 0.16 crash

### ISSUE THREAD

**Issue by niscinfo** [ovh/terraform-provider-ovh#233] opened 2021-11-09 12:56 UTC
Hi there,

Since a few days the terraform OVH provider 0.16 I use crashes. 
There was no upgrade of terraform (v 1.0.9) or either of the plugin. 
I managed to create OVH resources weeks ago , but now it seems to crash even at refresh. 

Here is the stack trace : 

```
Stack trace from the terraform-provider-ovh_v0.16.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xd6b12f]

goroutine 55 [running]:
github.com/ovh/terraform-provider-ovh/ovh.resourceOvhDomainZoneRecordRead(0xc000264a80, 0xeade60, 0xc0001819d0, 0x16c7a20, 0xc000058400)
	github.com/ovh/terraform-provider-ovh/ovh/resource_domain_zone_record.go:166 +0xcf
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000491b20, 0x1156cc8, 0xc000451940, 0xc000264a80, 0xeade60, 0xc0001819d0, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000491b20, 0x1156cc8, 0xc000451940, 0xc0000ba700, 0xeade60, 0xc0001819d0, 0xc00058e730, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000d6c8, 0x1156cc8, 0xc000451940, 0xc000451980, 0xc000451940, 0x40b965, 0xf3c780)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc0005a2420, 0x1156d70, 0xc000451940, 0xc000164240, 0xc0005a2420, 0xc0001637a0, 0xc0005c2ba0)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0xf787c0, 0xc0005a2420, 0x1156d70, 0xc0001637a0, 0xc0001641e0, 0x0, 0x1156d70, 0xc0001637a0, 0xc000113e60, 0x84)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00038c380, 0x115f9b8, 0xc0005af080, 0xc0001f1100, 0xc00011ec30, 0x1688570, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00038c380, 0x115f9b8, 0xc0005af080, 0xc0001f1100, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0003940d0, 0xc00038c380, 0x115f9b8, 0xc0005af080, 0xc0001f1100)
	google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-ovh_v0.16.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by yanndegat** [comment] 2021-11-09 13:20
hi @niscinfo 

this is a known bug of the provider <= v0.16.0 when ovh domain record ids have been changed by the ovh dns system.
(sometimes it happens that ovh changes the ids in its DBs)

the fact that the provider crashes will be fixed in the next release.

but it doesn't fix the root cause: the ids have changed in the ovh dns DB.
you will probably have to re import all new ids in your terraform existing state to completly fix your issue

**Comment by niscinfo** [comment] 2021-11-09 13:31
Hello Yanndegat, 
Thanks for the answer. 

Unfortunately there is a little problem : 
- To be able to import the object , it must be removed from the terraform state : 
```
terraform is already managing a remote object for ovh_domain_zone_record.XXXXX. To import to this address you must first remove the existing object from the state.
```
- When trying to remove it with "terraform destroy -target=<object>" , terraform tries to refresh the content of the object .. and it crashes ... 

Any idea of a workaround ?

**Comment by yanndegat** [comment] 2021-11-10 07:54
hi @niscinfo 

yes, removing from the state doesn't imply to "destroy" the resource

first, backup your state, then run the command:

```
terraform state rm ovh_domain_zone_record.XXXXX.
```

**Comment by niscinfo** [comment] 2021-11-12 08:04
Hi Yann, ,

Thanks for your help, the workaround helped. 
As the issue will be fixed in a next release, we can close this issue. 

Regards,

**Comment by niscinfo** [comment] 2021-11-12 08:05
Fixed in next releases and workaround for this version OK

**Closed** 2021-11-12 08:05 UTC
