### ISSUE TITLE
ovh_cloud_project_kube request OVH_CLOUD_PROJECT_SERVICE to be set

### ISSUE THREAD

**Issue by pc-jedi** [ovh/terraform-provider-ovh#187] opened 2021-04-03 11:39 UTC
The new `ovh_cloud_project_kube` resource requires the environment variable `OVH_CLOUD_PROJECT_SERVICE` to be set.
Previously it was possible to specify cloud_project resources by `<CLOUD_PROJECT_ID>/<RESOURCE_ID>`.
Also if it is not set no error occurs when trying to import a resource. You can only see the error when running with DEBUG enabled and see that the API call goes to `GET /1.0/cloud/project//kube/xxxxx` and return 404.

**Comment by amstuta** [comment] 2024-03-19 15:56
@pc-jedi for resource `ovh_cloud_project_kube`, you can either set the environment variable `OVH_CLOUD_PROJECT_SERVICE` or directly define `service_name` in your resource declaration. I just tested both and they work correctly, would you have a config / import command allowing to reproduce your issue ?

**Comment by amstuta** [comment] 2024-03-26 16:55
I close this issue since it's very old, don't hesitate to re-open it if the issue is still there.

**Closed by amstuta** 2024-03-26 16:55 UTC
