### ISSUE TITLE
[BUG] Resource "ovh_vrack_dedicated_server_interface" recreated every time

### ISSUE THREAD

**Issue by juluanb** [ovh/terraform-provider-ovh#479] opened 2023-10-11 16:21 UTC
### Describe the bug

Resource "ovh_vrack_dedicated_server_interface" recreated every time, even if arguments don't change.

### Terraform Version

```
Terraform v1.2.8
on linux_amd64
```

### OVH Terraform Provider Version

```
Initializing provider plugins...
...
- Installing ovh/ovh v0.34.0...
- Installed ovh/ovh v0.34.0 (signed by a HashiCorp partner, key ID F56D1A6CBDAAADA5)
...
```

### Affected Resource(s)

- ovh_vrack_dedicated_server_interface

### Terraform Configuration Files

```hcl
resource "ovh_vrack_dedicated_server_interface" "vdsi" {
  for_each = var.HOSTS

  service_name = var.VRACK_ID
  interface_id = [for i in data.ovh_dedicated_server.my_servers[each.key].vnis : i.uuid if i.mode == "vrack"][0]
}
```

### Expected Behavior

Not re-attaching the Dedicated Server Network Interface to the VRack if the service name and interface id don't change.

### Actual Behavior

The Dedicated Server Network Interface as always re-attached to the VRack, even is the interface id and the service name keep the same.

**Comment by yomovh** [comment] 2023-11-03 16:44
Hello,
I have not been able to reproduce the issue with a simple example. Can you please provide more details & debug execution logs ? 
Thanks

**Comment by yomovh** [comment] 2023-12-12 09:52
Since we do not have enough information, I will close the issue for cleaning. Do not hesite to reopen it when you can provide more information.

**Closed by yomovh** 2023-12-12 09:52 UTC
Labels: Status: Missing inputs, Product: Bare Metal

**Comment by juluanb** [comment] 2024-07-30 14:39
I was inspired by [this OVH configuration example](https://github.com/ovh/terraform-ovh-commons/blob/master/examples/k8s-sd-openstack/vrack/main.tf) to write my TF configuration, in a module:

```hcl
data "ovh_dedicated_server" "my_servers" {
  for_each = var.HOSTS

  service_name = each.key
}

resource "ovh_vrack_dedicated_server_interface" "vdsi" {
  for_each = var.HOSTS

  service_name = var.VRACK_ID
  interface_id = [for i in data.ovh_dedicated_server.my_servers[each.key].vnis : i.uuid if i.mode == "vrack"][0]
}
```

When I execute `terraform plan`, changes are detected, implying the re-association of the servers to the vrack:

```hcl
# module.my_dedicated_servers.module.my_dedicated_servers_install.ovh_vrack_dedicated_server_interface.vdsi["ns*******1.ip-***********.eu"] must be replaced
-/+ resource "ovh_vrack_dedicated_server_interface" "vdsi" {
      ~ id           = "vrack_pn-*******-dedicatedserverinterface_***************************a" -> (known after apply)
      ~ interface_id = "***************************" # forces replacement -> (known after apply) # forces replacement
        # (1 unchanged attribute hidden)
    }

# module.my_dedicated_servers.module.my_dedicated_servers_install.ovh_vrack_dedicated_server_interface.vdsi["ns*******2.ip-***********.eu"] must be replaced
-/+ resource "ovh_vrack_dedicated_server_interface" "vdsi" {
      ~ id           = "vrack_pn-*******-dedicatedserverinterface_***************************b" -> (known after apply)
      ~ interface_id = "372e9aa9-bbc6-4103-a725-6caa6265a1ab" # forces replacement -> (known after apply) # forces replacement
        # (1 unchanged attribute hidden)
    }
...
```
I was expected no changes here because my var.HOSTS keep the same value. This behavior implies that my dedicated servers will be de-associated from/re-associated to the vrack, losing their connections to other public instances also attached to the vrack (not shown here).

Note that this behavior is not always the same because when the plan is applied twice consecutively, no changes is detected the second time, meaning that the servers are not removed and added again to the vrack (which corresponds to what I expect). 

Did I miss something?
