### ISSUE TITLE
Domain A record is added, not updated

### ISSUE THREAD

**Issue by technicalflow** [ovh/terraform-provider-ovh#292] opened 2022-08-21 15:54 UTC
Hello there,

Using ovh_domain_zone_record terraform is adding second A record instead of changing current one.

My configuration for Azure:

resource "ovh_domain_zone_record" "testip" {
  zone      = var.domain_name
  subdomain = null
  fieldtype = "A"
  ttl       = "0"
  target    = data.azurerm_public_ip.pipread.ip_address

  depends_on = [
    azurerm_public_ip.pip
  ]
}

**Comment by coopengo-glecomte** [comment] 2022-10-14 15:23
Hi,

I have the same Issue, it's work when I edit the record on UI and just save it without any change.

I read the api documentation, and this resources looks missing the refresh action : 

[/domain/zone/{zoneName}/refresh](https://api.ovh.com/console/#/domain/zone/{zoneName}/refresh~POST)

**Comment by coopengo-glecomte** [comment] 2022-10-18 15:47
Hi,

Following my work to do a workaround with curl command, I realized that my token didn't have rights to refresh...

So the problem is maybe in the response which doesn't say anything about that ?

I did a new test with these rights, and now the DNS looks good.

I'll continue to perform some test to confirm that it's ok

**Comment by coopengo-glecomte** [comment] 2022-11-02 10:53
Hi, 

Following many tests on 2 lasts weeks, all work fine.

Just for your information, the following rights are need to work as expected : 

GET : /domain/zone/<your domain>/record/*
PUT: /domain/zone/<your domain>/record/*
DELETE: /domain/zone/<your domain>/record/*
GET: /domain/zone/<your domain>/record
POST: /domain/zone/<your domain>/record
POST: /domain/zone/<your domain>/refresh

**Comment by yomovh** [comment] 2022-12-19 14:24
@technicalflow : if terraform has not created the record but you need to update it then you need to import the record as stated in the [documentation](https://registry.terraform.io/providers/ovh/ovh/latest/docs/resources/ovh_domain_zone_record) 
I have proposed a [PR](https://github.com/ovh/terraform-provider-ovh/pull/348) in order to be clearer on how to get the zone record id

**Comment by yomovh** [comment] 2023-01-20 09:44
Closing the issue since the documentation have been updated in 0.26

**Closed by yomovh** 2023-01-20 09:44 UTC
Labels: Type: Documentation, 0.26.0, Product: Domain Names
