### ISSUE TITLE
Unable to use soyoustart endpoints

### ISSUE THREAD

**Issue by drgroot** [ovh/terraform-provider-ovh#163] opened 2020-10-14 14:20 UTC
```
provider "ovh" {
  endpoint = "soyoustart-ca"
}
```

Terraform Version: 0.13.4
ovh provider version: 0.9.1

Error: soyoustart-ca must be one of map[string]string{"kimsufi-ca":"https://ca.api.kimsufi.com/1.0", "kimsufi-eu":"https://eu.api.kimsufi.com/1.0", "ovh-ca":"https://ca.api.ovh.com/1.0", "ovh-eu":"https://eu.api.ovh.com/1.0", "ovh-us":"https://api.us.ovhcloud.com/1.0", "runabove-ca":"https://api.runabove.com/1.0", "soyoustart-ca":"https://ca.api.soyoustart.com/1.0", "soyoustart-eu":"https://eu.api.soyoustart.com/1.0"} endpoints

**Comment by pc-jedi** [comment] 2021-03-19 23:36
Late answer, but I guess this is a duplicate of #147 which was fixed with 0.10.0.

**Comment by dr4Ke** [comment] 2021-11-24 21:02
It was removed again at version 0.16.0 by 4f4d7c411f83d60e8e0a3f5d99983814c39c0d16

I don't understand why it was decided to be useless @yanndegat . I'm surely using it right now with version 0.15.0.

**Comment by yanndegat** [comment] 2021-11-25 07:48
hi @dr4Ke 

you're absolutely right, it's a mistake, i'll reintroduce them in next release.

the fact is that, in theory, these endoints shouldn't be located in the terraform-provider-ovh
but instead we should create a terraform-provider-soyoustart et and terraform-provider-kimsufi, pointing to the correct endpoints
and exposing only the resources available on these APIs.

**Comment by amstuta** [comment] 2024-03-20 11:23
Closing this issue since the provider should now be usable for Soyoustart and Kimsufi. Don't hesitate to reopen it if you still encounter issues.

**Closed by amstuta** 2024-03-20 11:23 UTC
