### ISSUE TITLE
Impossible to create a Swift container with 'history' versioning mode

### ISSUE THREAD

**Issue by SkypLabs** [ovh/terraform-provider-ovh#196] opened 2021-05-13 18:07 UTC
Hi there,

Terraform does not seem to accept the `history` versioning mode on a Swift object storage container and I do not know if the issue comes from OVH or the OpenStack provider.

### Terraform Version

```raw
Terraform v0.15.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/ovh/ovh v0.13.0
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.42.0
```

### Affected Resource(s)

- `openstack_objectstorage_container_v1`

### Terraform Configuration Files

```hcl
# https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/objectstorage_container_v1.
resource "openstack_objectstorage_container_v1" "terraform_state_files" {
  name   = "terraform-state-files"
  region = var.ovh_region

  versioning {
    # Copy the current version to the archive container then remove it from
    # the versioned container.
    #
    # See https://docs.openstack.org/swift/latest/api/object_versioning.html.
    type     = "history"
    location = openstack_objectstorage_container_v1.versioning.name
  }

  # Default: {}
  metadata = var.metadata
}

# https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/objectstorage_container_v1.
resource "openstack_objectstorage_container_v1" "versioning" {
  name   = "versioning"
  region = var.ovh_region

  # Default: {}
  metadata = var.metadata
}
```

### Debug Output

Given that the debugging trace contains some references to my project that I do not want to share publicly, please find attached a GPG-encrypted version of the output: [debug.gpg.log](https://github.com/ovh/terraform-provider-ovh/files/6474211/debug.gpg.log)

### Panic Output

N/A

### Expected Behavior

The object storage container's versioning mode should be set to `history`.

### Actual Behavior

The object storage container's versioning mode remains `versions` even after `terraform apply`.

### Steps to Reproduce

1. Run `terraform apply` to create the object storage containers.
2. Run `terraform plan` or `terraform apply` to see that the versioning mode currently in use is not the one described in the HCL file despite the previous `terraform apply`:

```raw
Terraform will perform the following actions:                                                                                                                                                                      

  # module.tfstate.openstack_objectstorage_container_v1.terraform_state_files will be updated in-place
  ~ resource "openstack_objectstorage_container_v1" "terraform_state_files" {
        id            = "terraform-state-files"
        name          = "terraform-state-files"
        # (3 unchanged attributes hidden)

      + versioning {
          + location = "versioning"
          + type     = "history"
        }
      - versioning {
          - location = "versioning" -> null
          - type     = "versions" -> null
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Important Factoids

N/A

### References

I have not found any issue related to this behaviour in the current repository nor in the one of the [OpenStack provider](https://github.com/terraform-provider-openstack/terraform-provider-openstack/).

**Comment by amstuta** [comment] 2024-03-28 09:50
@SkypLabs sorry for the late answer, I just tested your config and cannot reproduce, so I guess the problem has been resolved since.
I'm closing this issue, don't hesitate to re-open if still needed.

**Closed by amstuta** 2024-03-28 09:50 UTC
