### ISSUE TITLE
Creating "ovh_cloud_project" using v0.16.0 fails

### ISSUE THREAD

**Issue by khaledavarteq** [ovh/terraform-provider-ovh#229] opened 2021-10-29 07:58 UTC
Hello,

while trying to create a new Terraform module to manage an `ovh_cloud_project` resource, we ran into an issue:

### Terraform Version
Terraform v1.0.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/helm v2.3.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.6.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/ovh/ovh v0.16.0
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.44.0

### Affected Resource(s)
- ovh_cloud_project

### Terraform Configuration Files
```hcl
data "ovh_order_cart" "cart" {
  ovh_subsidiary = "fr"
  description    = "Use the French OVH cart by default"
}

data "ovh_order_cart_product_plan" "cloud" {
  cart_id        = data.ovh_order_cart.cart.id
  price_capacity = "renew"
  product        = "cloud"
  plan_code      = "project.2018"
}

resource "ovh_cloud_project" "cloud" {
  ovh_subsidiary = data.ovh_order_cart.cart.ovh_subsidiary
  description    = var.project_description
  payment_mean   = "fidelity"

  plan {
    duration     = data.ovh_order_cart_product_plan.cloud.selected_price.0.duration
    plan_code    = data.ovh_order_cart_product_plan.cloud.plan_code
    pricing_mode = data.ovh_order_cart_product_plan.cloud.selected_price.0.pricing_mode
  }
}
```

### Debug Output
```
module.ovh_cloud.ovh_cloud_project.cloud: Creating...

│ Error: Could not order cloud project: "calling Post /order/cart/cf35f36c-xxxx-xxxx-xxxx-1cc4885e14fd/checkout:\n\t \"Error 400: \\\"Found eligibility issues: challengePaymentMethod\\\"\""
│ 
│   with module.ovh_cloud.ovh_cloud_project.cloud,
│   on main.tf line 1, in resource "ovh_cloud_project" "cloud":
│    1: resource "ovh_cloud_project" "cloud" {
```

### Expected Behavior
A new cloud project should be created.

### Actual Behavior
Terraform does not create a new cloud project and aborts with the above error message.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
The above code is very similar to the documentation for the resource [ovh_cloud_project](https://registry.terraform.io/providers/ovh/ovh/latest/docs/resources/cloud_project) and yet the above error is returned. We have added a valid payment method and manually creating a cloud project works. We can also use the manually created cloud project's ID in other Terraform code without issue.

**Comment by loeken** [comment] 2021-11-19 12:39
I can confirm the same problem here

**Comment by cambierr** [comment] 2022-04-25 08:50
ping @mhurtrel maybe ? this is blocking us from creating a new hosting zone right now

**Comment by mhurtrel** [comment] 2022-04-25 16:00
@yanndegat @scraly could you have a look at this ?

**Comment by mhurtrel** [comment] 2022-04-26 12:05
We had a look and it seems this behaviour is triggered by a protection system :
If your paiement mean has not been used by humans for a long period, we need you to perform a manuel action in the manager - like ordering one project manually. This is to prevent customer which account would be hijacked and prevent any bad surprise.

After this manual one you should be able to order project via API again for a long period of time.
But the fact that 4 of you raise the issue make me wonder if we do not have false positive/ a bug raising this special behaviour with no reason.

@cambierr @loeken @elthariel @dbourcet would you mind DMing me the OVHcloud account (nichandle in the form xxx-ovh ) on Twitter : https://twitter.com/crazyman so that we gave a look. If you are not confortable with this, you can also open a OVHcloud support ticket and explicitely ask support to escalate this to me (Maxime Hurtrel), including a link to this discussion.

I officially close the issue as it is not a feature request (I confirm that the feature is working for most users) but a bug report.

**Comment by cambierr** [comment] 2022-04-26 14:41
@mhurtrel you can check business support ticket #5403146 which I opened yesterday since this is actually blocking no matter the payment mean usage: I created a project manually a few days ago, but still can't do it automatically via terraform NOR via API

available live (DM) via https://twitter.com/r_cambier or via the mobile phone linked to that ovh account

**Comment by dbourcet** [comment] 2022-04-27 09:41
@mhurtrel Since my like on the original post 6 months ago I left my company. I can't be of any help anymore.

**Comment by mhurtrel** [comment] 2022-04-27 09:57
Thanks for you input. We could identify the bug and this behaviour will be corrected soon.

**Comment by mhurtrel** [comment] 2022-05-10 07:49
Hello @cambierr @khaledavarteq and others.
We managed to get a first major improvment on this. You should now be able to create project as code again , but provided 2 conditions : 
> You should have at least 3 public cloud projects currently (note that tehre is a 3 project limit by default, which can be raised by a support ticket)
> You should have created a public cloud project during the last 3 months.

If one of this business rule is not met, you will receive the current error : "Found eligibility issues: challengePaymentMethod". In that case, the only solution is to use the web control panel (aka Manager) to create a project. You will then be presented a challenge to validate that you are indeed the owner of the payment mean used on your account (the challenge depends on the payment mean and other parameters). 

Can you confirm that works on your side ?

I hope you understand that this rule and extra human step has been put in place to avoid bad surprises for customers that leaked their ovhcloud credentials. We will try to continue improving those rules in the future to facilitate Inra-as-code scenarios, such as this "public cloud project as code" scenari.

**Comment by cambierr** [comment] 2022-05-11 07:06
Hello @mhurtrel and thanks for you quick feedback on this one.

I just tried and can't manage to go any further, having `500 Internal server error` during the `/order/cart/{cardId}/checkout` call

I thus retried and got the previous error `400 Found eligibility issues: challengePaymentMethod`

I think I do match both conditions you explained so I'm not sure to understand this one. Feel free to DM me on twitter or via the email linked to the OVH account we discussed together (the one with OVH id starting with cr2) if you think I can help in any way

**Comment by cambierr** [comment] 2022-05-11 12:14
Update: this was discussed out of band with @mhurtrel : I do confirm this is fixed and working

**Comment by mhurtrel** [comment] 2022-05-11 12:19
Thanks @cambierr  !
Closing the issue. Note that documentation will be updated soon by @scraly to specify the requirements described above.

**Closed by mhurtrel** 2022-05-11 12:19 UTC

**Comment by loeken** [comment] 2023-08-21 11:32
@mhurtrel "You should have at least 3 public cloud projects currently (note that there is a 3 project limit by default, which can be raised by a support ticket)" <- is there a plan to remove this requirement?

not everybody has 3+ projects in ovh, for example i have a client for whom i plan on setting up a kubernetes cluster in ovh, he is new to ovh. So i need to manually log in and create 3 projects ( and then not use them ) in order to create "projects" via terraform?

**Comment by loeken** [comment] 2023-08-21 11:33
also this information is nowhere to be found in the terraform docs and it took me quite a bit to find this new "requirement"

**Comment by mhurtrel** [comment] 2023-08-21 17:02
Hi @loeken and thanks for the heads up. I am not responsible for that par t but will make sure my colleagues clear this asap

**Comment by loeken** [comment] 2023-08-30 07:59
@mhurtrel any updates on this? should i raise a seperate issue for this ?
