### ISSUE TITLE
[BUG] Nodepool cannot be destroyed when status is scaling

### ISSUE THREAD

**Issue by kiweezi** [ovh/terraform-provider-ovh#404] opened 2023-04-03 16:33 UTC
### Describe the bug
When destroying a nodepool shortly after creating, the destruction fails as the nodepool is still upscaling.
`HTTP Error 400: Client::BadRequest: "[IntegrityError] 400: Cannot delete NodePool: NodePool status is UPSCALING`

### Terraform Version

```powershell
PS > terraform -v
Terraform v1.4.2
on windows_amd64
+ provider registry.terraform.io/hashicorp/helm v2.9.0
+ provider registry.terraform.io/hashicorp/http v3.2.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.18.1
+ provider registry.terraform.io/ovh/ovh v0.28.1

Your version of Terraform is out of date! The latest version
is 1.4.4. You can update by downloading from https://www.terraform.io/downloads.html
```

### OVH Terraform Provider Version

```powershell
PS > terraform init

Initializing Terraform Cloud...

Initializing provider plugins...
- Reusing previous version of hashicorp/http from the dependency lock file
- Reusing previous version of hashicorp/kubernetes from the dependency lock file
- Reusing previous version of ovh/ovh from the dependency lock file
- Reusing previous version of hashicorp/helm from the dependency lock file
- Using previously-installed hashicorp/http v3.2.1
- Using previously-installed hashicorp/kubernetes v2.18.1
- Using previously-installed ovh/ovh v0.28.1
- Using previously-installed hashicorp/helm v2.9.0

Terraform Cloud has been successfully initialized!

You may now begin working with Terraform Cloud. Try running "terraform plan" to
see any changes that are required for your infrastructure.

If you ever set or change modules or Terraform Settings, run "terraform init"
again to reinitialize your working directory.
```

### Affected Resource(s)

- ovh_cloud_project_kube_nodepool

### Terraform Configuration Files

```hcl
resource "ovh_cloud_project_kube_nodepool" "main" {
  for_each      = toset(local.nodes_required)

  service_name  = var.project_id
  kube_id       = ovh_cloud_project_kube.main.id
  # OVH nodepool names don't support underscores.
  name          = replace("np_${local.common_name}_main", "_", "-")
  flavor_name   = "d2-8"
  
  autoscale     = true
  max_nodes     = 1
  min_nodes     = 0

  template {
    spec {
      taints = [
        # The ratio of resources required.
        # CPU:Memory.
        {
          effect = "NoSchedule"
          key    = "ratio"
          value  = "1-2"
        }
      ]
    }
  }
}
```

### Debug Output

[Link to gist](https://gist.github.com/kiweezi/f935986c994e04cb4b6cc2e05e52816a#file-tf-nodepool-bug-md).

### Expected Behavior

The nodepool is destroyed.
Preferably the destruction request would wait for the scaling to finish, before continuing to destroy the nodepool.

### Actual Behavior

The nodepool was not destroyed and the Terraform run failed.

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. Deploy a nodepool.
2. Prompt the nodepool to scale e.g. deploy pods with kubernetes.
3. While the nodepool is scaling, destroy the nodepool.

### References

Not that I could find, sorry if I've missed any.

### Additional context

This is an issue because I run Terraform tests on PR.
If tests succeed without problems, the nodepool is destroyed shortly after being created, which triggers this bug.

It would be nice if this exception could be handled by waiting for the scaling to finish as part of the destruction of the nodepool.

**Comment by yomovh** [comment] 2023-04-04 06:51
Thanks for your issue. I have redirected it to the product team.

**Comment by matprig** [comment] 2023-04-05 12:48
Hello, indeed you cannot destroy a cluster while is scaling (up or down).

Terraform provider is directly link to API behavior. 

IMO there is no reason to add specific functional behavior to terraform provider for external test purposes that triggers the autoscaler.

I imagine that if you running tests with the help of terraform you can implement wait condition until the state of the nodepool is READY.

best,

**Comment by kiweezi** [comment] 2023-04-06 09:48
Hey! Thanks for your reply.

I would like to clarify that the error actually comes from [**attempting to destroy the nodepool while it is scaling**](https://gist.github.com/kiweezi/f935986c994e04cb4b6cc2e05e52816a#file-tf-nodepool-bug-md).
This is **not my intention** to do, however it is the behaviour which this Terraform provider resource performs.
In my opinion this is not intentional behaviour, as I'm sure most people would agree that deleting a nodepool during scaling would not succeed.

I would prefer to wait until it finishes scaling, which is what I am asking for as the fix for this bug.

The nodepool resource knows the the status, that it's being requested to be deleted and that if it does so, it will result in a failure. Therefore it would make most sense to catch this and handle it correctly, by waiting for the status to be ready, in this resource.

Additionally I did some research into working around this issue, but I do not think this is possible within Terraform. The two ideas which fail are:
- Custom condition checks - can only produce errors, not change resource behaviour
- Using an API request into a null resource - cannot change resource behaviour

You commented that the fundamental issue may stem from the API, and I'm happy to request this to be changed instead. Where would I need to go to request this?

**Comment by matprig** [comment] 2023-04-07 09:53
hello,

In fact i not sure to understand what you are trying to do, the TF configuration file you provide is just a node pool and output given is just the error returned by the API.

I don't have the global view and cannot reproduce, for example i don't know what/how/why triggers the autoscaling.

best

**Comment by yomovh** [comment] 2023-05-11 14:06
Closing the issue since we are lacking some inputs

**Closed by yomovh** 2023-05-11 14:06 UTC
Labels: Type: Bug, Product: Managed Kubernetes Service, Status: Missing inputs
