### ISSUE TITLE
Randomly failing creation ovh_cloud_project_network_private resource.

### ISSUE THREAD

**Issue by qmartouzet** [ovh/terraform-provider-ovh#320] opened 2022-09-29 16:06 UTC
### Terraform Version

1.2.8

### Affected Resource(s)

ovh_cloud_project_network_private

### Terraform Configuration Files

```hcl
# Create Internal VLAN
resource "ovh_cloud_project_network_private" "vlan_internal" {
  service_name = local.project_id
  name         = "${var.ENV_PREFIX}-vlan-internal"
  vlan_id      = var.VLAN_INTERNAL_ID
  depends_on   = [ovh_vrack_cloudproject.vcp] # Dépend de l'association du vrack au projet cloud
  regions      = ["SBG5"]
}
```

### Expected Behavior

Ressource is created.

### Actual Behavior

Creation fail with HTTP 404 after 30s : 
```
module.network.module.network_vlan.ovh_cloud_project_network_private.vlan_internal: Creating...
module.network.module.network_vlan.ovh_cloud_project_network_private.vlan_internal: Still creating... [10s elapsed]
module.network.module.network_vlan.ovh_cloud_project_network_private.vlan_internal: Still creating... [20s elapsed]
╷
│ Error: waiting for private network (projectId: xxxxxxxxxxxxxxxxxxxx, vlanId:100, name: vlan-internal, regions: [SBG5]): Error 404: "The requested network (id = pn-xxxxxxx_100) does not exist"
│ 
│   with module.network.module.network_vlan.ovh_cloud_project_network_private.vlan_internal,
│   on ../../modules/network_vlan/main.tf line 30, in resource "ovh_cloud_project_network_private" "vlan_internal":
│   30: resource "ovh_cloud_project_network_private" "vlan_internal" {
│ 
╵
```

When running once again the script, resource fail again as it already exists... 

```
module.network.module.network_vlan.ovh_cloud_project_network_private.vlan_internal: Creating...
╷
│ Error: calling /cloud/project/xxxxxxxxxxxxxxxxxxxx/network/private with params projectId: xxxxxxxxxxxxxxxxxxxx, vlanId:100, name: vlan-internal, regions: [SBG5]:
│ 	 "Error 400: \"A private network already exists for this vlan ID (network id pn-xxxxxxx_100)\""
│ 
│   with module.network.module.network_vlan.ovh_cloud_project_network_private.vlan_internal,
│   on ../../modules/network_vlan/main.tf line 30, in resource "ovh_cloud_project_network_private" "vlan_internal":
│   30: resource "ovh_cloud_project_network_private" "vlan_internal" {
│ 
╵
```

Importing the created resource resolved the problem.

It seems that sometime the resource creation process don't wait enough time before checking if resource is ready. It could lead to unexpected failure of CI jobs.

### Steps to Reproduce

1. `terraform apply`

**Comment by d0x2f** [comment] 2022-11-15 14:33
I'm facing this issue as well. I think a simple solution would be to consider 404 responses to be the same as a 'not ready' status in this method: https://github.com/ovh/terraform-provider-ovh/blob/cdf350164c2de468a792673b8da9efa2a6dfa143/ovh/resource_cloud_project_network_private.go#L272

**Comment by yomovh** [comment] 2023-01-25 15:52
The backend API have been fixed. I am not able to reproduce the issue any more. 
Closing the issue.

**Closed by yomovh** 2023-01-25 15:52 UTC
Labels: Product: Network, Status: Backlog
